### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Bernankez** [Bernankez/theme-generator#1]
#### Features

- [x] #4
- [ ] Website: undo/redo function
- [x] #2
- [x] Website: improve real-time preview website example #2
- [ ] Website: add built-in themes
- [ ] Core: DaisyUI preset
- [ ] Website: provide a entry to clear cache
- [ ] Website: better string compression [https://github.com/vuejs/repl/blob/main/src/utils.ts](https://github.com/vuejs/repl/blob/main/src/utils.ts)

#### Bug Fixes

- [ ] Website: restore to the correct current selected template after a template is restored
